modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/AmbientSounds/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="ambientsounds"
    logoFile="ambientsounds.png"
    version="5.3.7"
    displayName="AmbientSounds"
    displayURL="https://modrinth.com/mod/ambientsounds"
    authors="CreativeMD"
    description='''Expands minecraft's ambient sounds.'''

[[dependencies.ambientsounds]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambientsounds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambientsounds]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="[2.11.9,)"

